; ============================================================
;  PlatformIO Project Configuration File
;  Dự án: ESP32 - Giám sát môi trường phòng thời gian thực
; ============================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; Dùng LittleFS cho giao diện web.
; default.csv cấp vùng filesystem lớn hơn cho toàn bộ giao diện + PWA assets.
board_build.filesystem = littlefs
board_build.partitions = default.csv

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1

lib_deps =
    adafruit/Adafruit SHT31 Library@^2.2.2
    adafruit/Adafruit Unified Sensor@^1.1.14
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SSD1306@^2.5.9
    https://github.com/sparkfun/SparkFun_Indoor_Air_Quality_Sensor-ENS160_Arduino_Library.git
    ESP32Async/ESPAsyncWebServer@^3.1.0
    ESP32Async/AsyncTCP@^3.4.0
    ayushsharma82/ElegantOTA@^3.1.1

monitor_filters = esp32_exception_decoder, colorize
